"""
Main entry point for the Langchain/Langgraph autonomous development system
"""
import os
import sys
import argparse
from pathlib import Path

# Add the parent directory to the path so we can import from the same level
sys.path.append(str(Path(__file__).parent))

from config import Config
from state import State
from workflow import run_autonomous_development, create_initial_state
from datetime import datetime

def setup_project_directory(config: Config):
    """Set up the project directory structure"""
    print(f"Setting up project directory: {config.project_dir}")
    
    # Create project directory if it doesn't exist
    Path(config.project_dir).mkdir(parents=True, exist_ok=True)
    
    # Create subdirectories
    dirs_to_create = [
        os.path.join(config.project_dir, "frontend"),
        os.path.join(config.project_dir, "server"), 
        os.path.join(config.project_dir, "screenshots"),
        os.path.join(config.project_dir, "docs")
    ]
    
    for dir_path in dirs_to_create:
        Path(dir_path).mkdir(parents=True, exist_ok=True)
        print(f"Created directory: {dir_path}")

def copy_app_spec_to_project(config: Config, app_spec_path: str = None):
    """Copy or create the app specification file in the project directory"""
    if app_spec_path is None:
        # Use the example from the source directory
        app_spec_path = "/workspace/source/app_spec_example.txt"
    
    dest_path = os.path.join(config.project_dir, config.app_spec_file)
    
    if os.path.exists(app_spec_path):
        # Copy the file
        with open(app_spec_path, 'r', encoding='utf-8') as src:
            content = src.read()
        
        with open(dest_path, 'w', encoding='utf-8') as dest:
            dest.write(content)
        
        print(f"Copied app spec to: {dest_path}")
    else:
        # Create a basic app spec if the source doesn't exist
        basic_spec = """<project_specification>
  <project_name>Autonomous Development Project</project_name>
  
  <overview>
    This is an autonomous development project generated by the Langgraph system.
    The system will implement features based on this specification.
  </overview>
  
  <technology_stack>
    <frontend>React with Vite</frontend>
    <backend>Node.js with Express</backend>
    <database>SQLite</database>
  </technology_stack>
  
  <core_features>
    <feature>
      <name>Basic UI</name>
      <description>Implement a basic user interface</description>
    </feature>
    <feature>
      <name>API Integration</name>
      <description>Connect frontend to backend API</description>
    </feature>
  </core_features>
</project_specification>"""
        
        with open(dest_path, 'w', encoding='utf-8') as dest:
            dest.write(basic_spec)
        
        print(f"Created basic app spec at: {dest_path}")

def main():
    parser = argparse.ArgumentParser(description='Langgraph Autonomous Development System')
    parser.add_argument('--project-dir', type=str, default='./project',
                       help='Project directory path')
    parser.add_argument('--app-spec', type=str,
                       help='Path to app specification file')
    parser.add_argument('--model', type=str, default='local-20b-model',
                       help='Model name for the LLM')
    parser.add_argument('--frontend-port', type=int, default=3000,
                       help='Frontend port')
    parser.add_argument('--backend-port', type=int, default=8000,
                       help='Backend port')
    
    args = parser.parse_args()
    
    # Create config
    config = Config(
        project_dir=args.project_dir,
        llm_model_name=args.model,
        frontend_port=args.frontend_port,
        backend_port=args.backend_port
    )
    
    print(f"Starting autonomous development system")
    print(f"Project directory: {config.project_dir}")
    print(f"LLM model: {config.llm_model_name}")
    print(f"Ports: Frontend {config.frontend_port}, Backend {config.backend_port}")
    
    # Set up project directory
    setup_project_directory(config)
    
    # Copy app spec to project directory
    copy_app_spec_to_project(config, args.app_spec)
    
    # Create initial state
    initial_state = create_initial_state("initializer", config.project_dir)
    initial_state.add_progress_log(f"Started autonomous development at {datetime.now().isoformat()}")
    
    print("Starting development workflow...")
    
    try:
        # Run the autonomous development process
        final_state = run_autonomous_development(config)
        
        print(f"\nDevelopment workflow completed!")
        print(f"Final status: {final_state.status}")
        print(f"Features completed: {final_state.completed_features}/{final_state.total_features}")
        print(f"Completion percentage: {final_state.get_completion_percentage():.1f}%")
        
        if final_state.errors:
            print(f"Errors encountered: {len(final_state.errors)}")
            for error in final_state.errors[-5:]:  # Show last 5 errors
                print(f"  - {error}")
        
        if final_state.warnings:
            print(f"Warnings: {len(final_state.warnings)}")
            for warning in final_state.warnings[-5:]:  # Show last 5 warnings
                print(f"  - {warning}")
                
    except KeyboardInterrupt:
        print("\nDevelopment process interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\nError during development process: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()